#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <limits>
#include <tuple>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>
#define REP(k,a) for(int k=0; k < (a); ++k)
#define REPP(k,a,b) for(int k= (a); k < (b); ++k)
#define INF 200000000
#define mp make_pair
#define len(s) (int)((s).size())
#define pb push_back
#define all(X) (X).begin(), (X).end()
using namespace std;
typedef long long ll;
using vi = vector<int>;
using vii = vector<vector<int>>;
using pii = pair<int,int>;


class RobotOnMoon {
public:
	int longestSafeCommand(vector <string> board) {
		int py=0, px=0;
		REP(y, len(board)){
			REP(x, len(board[0])){
				if(board[y][x] == 'S'){
					py = y;
					px = x;
				}
			}
		}
		REP(i, len(board)){
			if(board[i][px] == '#')
				return -1;
		}
		REP(i, len(board[0])){
			if(board[py][i] == '#')
				return -1;
		}
		return len(board)+len(board[0])-2;
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit-pf 2.3.0
#include <iostream>
#include <string>
#include <vector>
#include <ctime>
#include <cmath>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <string> p0, bool hasAnswer, int p1) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p0[i] << "\"";
	}
	cout << "}";
	cout << "]" << endl;
	RobotOnMoon *obj;
	int answer;
	obj = new RobotOnMoon();
	clock_t startTime = clock();
	answer = obj->longestSafeCommand(p0);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p1 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p1;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	bool disabled;
	bool tests_disabled;
	all_right = true;
	tests_disabled = false;
	
	vector <string> p0;
	int p1;
	
	// ----- test 0 -----
	disabled = false;
	p0 = {"#####","#...#","#.S.#","#...#","#####"};
	p1 = -1;
	all_right = (disabled || KawigiEdit_RunTest(0, p0, true, p1) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 1 -----
	disabled = false;
	p0 = {"S......"};
	p1 = 6;
	all_right = (disabled || KawigiEdit_RunTest(1, p0, true, p1) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 2 -----
	disabled = false;
	p0 = {"#.######","#.#..S.#","#.#.##.#","#......#","########"};
	p1 = -1;
	all_right = (disabled || KawigiEdit_RunTest(2, p0, true, p1) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 3 -----
	disabled = false;
	p0 = {"S"};
	p1 = 0;
	all_right = (disabled || KawigiEdit_RunTest(3, p0, true, p1) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	if (all_right) {
		if (tests_disabled) {
			cout << "You're a stud (but some test cases were disabled)!" << endl;
		} else {
			cout << "You're a stud (at least on given cases)!" << endl;
		}
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// There is a robot on the moon.
// You are given a vector <string> board containing the map of a rectangular area.
// The robot is currently located somewhere in that area.
// In the map, the character '.' (period) represents an empty square, 'S' represents an empty square that currently contains the robot, and '#' represents an obstacle.
// 
// 
// We are going to send a sequence of commands to the robot.
// Each command must be one of 'U', 'D', 'L', and 'R', representing a step up, down, left, and right, respectively.
// 
// 
// Whenever the robot receives a command, one of three things will happen:
// 
// If the requested move leads to an empty square, the robot performs the move.
// If the requested move leads to a square with an obstacle, the robot ignores the command and remains in place.
// If the requested move leads out of the mapped area, the robot leaves the mapped area and dies immediately.
// 
// 
// 
// A sequence of commands is called safe if the robot is still alive after executing the entire sequence.
// 
// 
// When sending commands to the moon, some of them may get lost along the way.
// This may sometimes change a safe sequence of commands into an unsafe one.
// We want to avoid that.
// 
// 
// A sequence of commands is called perfectly safe if it is safe, and each of its subsequences is safe as well.
// (Note that this includes subsequences that are not contiguous.)
// 
// 
// Find and return the largest X such that there is a perfectly safe sequence of X commands.
// If there are arbitrarily long perfectly safe sequences, return -1 instead.
// 
// DEFINITION
// Class:RobotOnMoon
// Method:longestSafeCommand
// Parameters:vector <string>
// Returns:int
// Method signature:int longestSafeCommand(vector <string> board)
// 
// 
// NOTES
// -The direction 'U' corresponds to moving from board[i][j] to board[i-1][j]. The direction 'L' corresponds to moving from board[i][j] to board[i][j-1].
// 
// 
// CONSTRAINTS
// -board will contain between 1 and 50 elements, inclusive.
// -Each element of board will contain between 1 and 50 characters.
// -Each element of board will contain same number of characters.
// -The characters in board will be '.', '#' or 'S'.
// -There will be exactly one 'S' in board.
// 
// 
// EXAMPLES
// 
// 0)
// {"#####",
//  "#...#",
//  "#.S.#",
//  "#...#",
//  "#####"}
// 
// Returns: -1
// 
// There are obstacles all around the map. This means that all possible sequences of commands are perfectly safe.
// 
// 1)
// {"S......"}
// 
// Returns: 6
// 
// The longest perfectly safe string is "RRRRRR"
// 
// 2)
// {"#.######",
//  "#.#..S.#",
//  "#.#.##.#",
//  "#......#",
//  "########"}
// 
// Returns: -1
// 
// Even though it is possible to leave this map, there are still arbitrarily long perfectly safe sequences of commands. For example, any sequence that does not contain any 'U' is perfectly safe.
// 
// 3)
// {"S"}
// 
// Returns: 0
// 
// 
// 
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit-pf 2.3.0!
