#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <limits>
#include <tuple>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>
#define REP(k,a) for(int k=0; k < (a); ++k)
#define INF 200000000
#define mp make_pair
#define len(s) (int)((s).size())
#define pb push_back
using namespace std;
typedef long long ll;
typedef unsigned int uint;
using vi = vector<int>;
using vii = vector<vector<int>>;
using pii = pair<int,int>;

class TaroFillingAStringDiv1 {
public:
	int getNumber(int N, vector <int> position, string value) {
		vector<pair<int,char>> S;
		REP(i, len(position)){
			S.pb(mp(position[i], value[i]));
		} 
		sort(S.begin(), S.end());
		int ans=1;
		REP(i, len(S)-1){
			int d = S[i+1].first-S[i].first-1;
			if(S[i+1].second == S[i].second && d % 2 == 0){
				ans = (ll(ans)*(d+1)) % 1000000007; 
			}
			if(S[i+1].second != S[i].second && d % 2 == 1){
				ans = (ll(ans)*(d+1)) % 1000000007; 
			}
		}
		return ans;
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit-pf 2.3.0
#include <iostream>
#include <string>
#include <vector>
#include <ctime>
#include <cmath>
using namespace std;
bool KawigiEdit_RunTest(int testNum, int p0, vector <int> p1, string p2, bool hasAnswer, int p3) {
	cout << "Test " << testNum << ": [" << p0 << "," << "{";
	for (int i = 0; int(p1.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p1[i];
	}
	cout << "}" << "," << "\"" << p2 << "\"";
	cout << "]" << endl;
	TaroFillingAStringDiv1 *obj;
	int answer;
	obj = new TaroFillingAStringDiv1();
	clock_t startTime = clock();
	answer = obj->getNumber(p0, p1, p2);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p3 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p3;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	bool disabled;
	bool tests_disabled;
	all_right = true;
	tests_disabled = false;
	
	int p0;
	vector <int> p1;
	string p2;
	int p3;
	
	// ----- test 0 -----
	disabled = false;
	p0 = 3;
	p1 = {1,3};
	p2 = "AB";
	p3 = 2;
	all_right = (disabled || KawigiEdit_RunTest(0, p0, p1, p2, true, p3) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 1 -----
	disabled = false;
	p0 = 4;
	p1 = {2,1,3,4};
	p2 = "ABBA";
	p3 = 1;
	all_right = (disabled || KawigiEdit_RunTest(1, p0, p1, p2, true, p3) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 2 -----
	disabled = false;
	p0 = 25;
	p1 = {23,4,8,1,24,9,16,17,6,2,25,15,14,7,13};
	p2 = "ABBBBABABBAAABA";
	p3 = 1;
	all_right = (disabled || KawigiEdit_RunTest(2, p0, p1, p2, true, p3) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 3 -----
	disabled = false;
	p0 = 305;
	p1 = {183,115,250,1,188,193,163,221,144,191,92,192,58,215,157,187,227,177,206,15,272,232,49,11,178,59,189,246};
	p2 = "ABAABBABBAABABBBBAAAABBABBBA";
	p3 = 43068480;
	all_right = (disabled || KawigiEdit_RunTest(3, p0, p1, p2, true, p3) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	if (all_right) {
		if (tests_disabled) {
			cout << "You're a stud (but some test cases were disabled)!" << endl;
		} else {
			cout << "You're a stud (at least on given cases)!" << endl;
		}
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// 
// Cat Taro likes strings.
// He is currently constructing a string S of length N.
// Each character of S will be either 'A' or 'B'.
// Taro has already chosen some of the characters.
// You are given these choices as a vector <int> position and a string value.
// For each valid i, the character at the 1-based index position[i] in S is the character value[i].
// 
// 
// 
// 
// To Taro, the ugliness of a string is the number of pairs of equal consecutive characters.
// For example, the ugliness of "ABABAABBB" is 3: there is one pair "AA" and two (overlapping) pairs "BB".
// 
// 
// 
// 
// Taro now wants to finish S by filling in the remaining characters.
// His goal is to create a string with the smallest possible ugliness.
// Let X be the number of possible strings Taro may produce.
// Return the value (X modulo 1,000,000,007).
// 
// 
// DEFINITION
// Class:TaroFillingAStringDiv1
// Method:getNumber
// Parameters:int, vector <int>, string
// Returns:int
// Method signature:int getNumber(int N, vector <int> position, string value)
// 
// 
// CONSTRAINTS
// -N will be between 1 and 1,000,000,000, inclusive.
// -position will contian between 1 and 50 elements, inclusive.
// -value and position will contain the same number of elements.
// -Each element of position will be between 1 and N, inclusive.
// -All elements of position will be distinct.
// -value will consist only of characters 'A' and 'B'.
// 
// 
// EXAMPLES
// 
// 0)
// 3
// {1, 3}
// "AB"
// 
// Returns: 2
// 
// Currently, Taro's string looks as follows: A_B.
// He can either produce the string AAB or the string ABB.
// Both have the same ugliness.
// 
// 1)
// 4
// {2, 1, 3, 4}
// "ABBA"
// 
// Returns: 1
// 
// All characters of S have already been chosen.
// 
// 2)
// 25
// {23, 4, 8, 1, 24, 9, 16, 17, 6, 2, 25, 15, 14, 7, 13}
// "ABBBBABABBAAABA"
// 
// Returns: 1
// 
// 
// 
// 3)
// 305
// {183, 115, 250, 1, 188, 193, 163, 221, 144, 191, 92, 192, 58, 215, 157, 187, 227, 177, 206, 15, 272, 232, 49, 11, 178, 59, 189, 246}
// "ABAABBABBAABABBBBAAAABBABBBA"
// 
// Returns: 43068480
// 
// 
// 
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit-pf 2.3.0!
