#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <limits>
#include <tuple>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;


class TrianglesContainOrigin {
public:
	long long count(vector <int> x, vector <int> y) {
        long long ans=0;
        vector<double> angles;
		for(int i=0; i<x.size(); i++){
            angles.push_back(atan2(y[i],x[i]));
        }
        sort(angles.begin(), angles.end());

        for(int i=0; i<x.size();i++){
            for(int j=i+1;j<x.size();j++){
                double alpha = angles[i];
                double beta = angles[j];
                if(beta-alpha >= M_PI) continue;
                auto start = lower_bound(angles.begin(), angles.end(), alpha+M_PI);
                auto end = upper_bound(angles.begin(), angles.end(), beta+M_PI);
                ans += distance(start,end);
            }
        }
        return ans;
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit-pf 2.3.0
#include <iostream>
#include <string>
#include <vector>
#include <ctime>
#include <cmath>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <int> p0, vector <int> p1, bool hasAnswer, long long p2) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p0[i];
	}
	cout << "}" << "," << "{";
	for (int i = 0; int(p1.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p1[i];
	}
	cout << "}";
	cout << "]" << endl;
	TrianglesContainOrigin *obj;
	long long answer;
	obj = new TrianglesContainOrigin();
	clock_t startTime = clock();
	answer = obj->count(p0, p1);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p2 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p2;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	bool disabled;
	bool tests_disabled;
	all_right = true;
	tests_disabled = false;
	
	vector <int> p0;
	vector <int> p1;
	long long p2;
	
	// ----- test 0 -----
	disabled = false;
	p0 = {-1,-1,1};
	p1 = {1,-1,0};
	p2 = 1ll;
	all_right = (disabled || KawigiEdit_RunTest(0, p0, p1, true, p2) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 1 -----
	disabled = false;
	p0 = {-1,-1,1,2};
	p1 = {1,-1,2,-1};
	p2 = 2ll;
	all_right = (disabled || KawigiEdit_RunTest(1, p0, p1, true, p2) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 2 -----
	disabled = false;
	p0 = {-1,-2,3,3,2,1};
	p1 = {-2,-1,1,2,3,3};
	p2 = 8ll;
	all_right = (disabled || KawigiEdit_RunTest(2, p0, p1, true, p2) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	// 
// 
	// ----- test 3 -----
	disabled = false;
    p0 = {1,5,10,5,-5,7,-9,-6,-3,0,8,8,1,-4,7,-3,10,9,-6};
    p1 = {5,-6,-3,4,-2,-8,-7,2,7,4,2,0,-4,-8,7,5,-5,-2,-9};
	p2 = 256ll;
	all_right = (disabled || KawigiEdit_RunTest(3, p0, p1, true, p2) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------

    // ----- test 3 -----
    disabled = true;
    p0 = {};
    p1 = {};
    for(int i=1; i<2500;i++){
        p0.push_back(i);
        p1.push_back(i);

    }
    p2 = 256ll;
    all_right = (disabled || KawigiEdit_RunTest(3, p0, p1, true, p2) ) && all_right;
    tests_disabled = tests_disabled || disabled;
    // ------------------
    	
	if (all_right) {
		if (tests_disabled) {
			cout << "You're a stud (but some test cases were disabled)!" << endl;
		} else {
			cout << "You're a stud (at least on given cases)!" << endl;
		}
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// We have chosen a finite set of points in the plane.
// You are given their coordinates in the vector <int>s x and y:
// for each valid i, there is a point with coordinates (x[i],y[i]).
// 
// We are interested in triangles with the following properties:
// 
// Each vertex of the triangle is one of our chosen points.
// The point (0,0) lies inside the triangle.
// 
// Return the number of such triangles.
// 
// Note that the constraints guarantee that there are no degenerate triangles and that the point (0,0) never lies on the boundary of a triangle.
// 
// 
// DEFINITION
// Class:TrianglesContainOrigin
// Method:count
// Parameters:vector <int>, vector <int>
// Returns:long long
// Method signature:long long count(vector <int> x, vector <int> y)
// 
// 
// CONSTRAINTS
// -x and y will contain between 3 and 2500 elements, inclusive.
// -x and y will contain the same number of elements.
// -Each element of x and y will be between -10,000 and 10,000, inclusive.
// -No two points will be the same.
// -No three points will be collinear.
// -No point will be on the origin.
// -There will be no two points P and Q such that P, Q, and the origin are collinear.
// 
// 
// EXAMPLES
// 
// 0)
// {-1,-1,1}
// {1,-1,0}
// 
// Returns: 1
// 
// There is exactly one possible triangle. It does contain the origin.
// 
// 1)
// {-1,-1,1,2}
// {1,-1,2,-1}
// 
// Returns: 2
// 
// There are four possible triangles. Two of them contain the origin. One is the triangle with vertices in (-1,1), (-1,-1), and (2,-1). The other is the triangle with vertices in (-1,-1), (1,2), and (2,-1).
// 
// 2)
// {-1,-2,3,3,2,1}
// {-2,-1,1,2,3,3}
// 
// Returns: 8
// 
// 
// 
// 3)
// {1,5,10,5,-5,7,-9,-6,-3,0,8,8,1,-4,7,-3,10,9,-6}
// {5,-6,-3,4,-2,-8,-7,2,7,4,2,0,-4,-8,7,5,-5,-2,-9}
// 
// Returns: 256
// 
// 
// 
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit-pf 2.3.0!
