#!/bin/bash
mkdir "../$1"
cp template.cc "../$1/a.cc"
cp template.cc "../$1/b.cc"
cp template.cc "../$1/c.cc"
cp template.cc "../$1/d.cc"
cp template.cc "../$1/e.cc"
cp test.sh "../$1/test.sh"
chmod 777 "../$1/test.sh"
touch "../$1/a.in"
touch "../$1/b.in"
touch "../$1/c.in"
touch "../$1/d.in"
touch "../$1/e.in"
cd "../$1"